// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class JunitTest1b {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void test1b() {
    // Test name: 1b)
    // Step # | name | target | value
    // 1 | open | https://www.calculator.net/ | 
    driver.get("https://www.calculator.net/");
    // 2 | setWindowSize | 769x691 | 
    driver.manage().window().setSize(new Dimension(769, 691));
    // 3 | click | linkText=Random Number Generator | 
    driver.findElement(By.linkText("Random Number Generator")).click();
    // 4 | click | name=supper | 
    driver.findElement(By.name("supper")).click();
    // 5 | type | name=supper | 10
    driver.findElement(By.name("supper")).sendKeys("10");
    // 6 | click | name=x | 
    driver.findElement(By.name("x")).click();
    // 7 | click | css=.verybigtext | 
    driver.findElement(By.cssSelector(".verybigtext")).click();
    // 8 | assertText | css=.verybigtext | 2
    assertThat(driver.findElement(By.cssSelector(".verybigtext")).getText(), is("2"));
  }
}